//NAME:VANSHIKA VERMA
//GUESS THE NUMBER GAME
//the system generates a random number from range 1 to 100.
//the user is prompted to guess the generated number.
//the system then compares if  the guess matches with the generated number or it is higher/lower.

import java.util.*;

public class GuessGame {
	
	public static void main(String[] args) {
	Scanner sc= new Scanner(System.in);
	int attempts=5,max=100,min=1,score;                   //no of attempts is limited to 5
	int randomNum=(int)(Math.random()*(max-min+1)+min);   //random number being generated by the system
    System.out.println("you have only 5 attempts to guess the number"); 
    int chance=1;
	while(attempts>0) {
		score=5;         //the score is displayed 5 if the user guesses the right number in first attempt
		System.out.println("enter your guess"+chance);
		int guess=sc.nextInt();
		if(guess==randomNum) {
			System.out.println("you are correct");
			System.out.println("your score is:"+score); 
			System.out.println("you won!");
			break;
		}
		else if(guess>randomNum) {
			System.out.println("your guess is higher than the generated number \n your score is 0!");
		}
		else
			System.out.println("your score is lower than the generated number \n your score is 0!");
		score--;
		attempts--;
		chance++;
	}
	System.out.println("the generated number was:"+randomNum);
	

	}

}
